/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface AssetChainManagerInterface extends utils.Interface {
  functions: {
    "addSupportedAsset(address,address)": FunctionFragment;
    "admin()": FunctionFragment;
    "deployReceiver(address,uint16)": FunctionFragment;
    "getMinimumDeposit(address)": FunctionFragment;
    "minimumDeposit(address)": FunctionFragment;
    "participatingInterface()": FunctionFragment;
    "portal()": FunctionFragment;
    "receiver()": FunctionFragment;
    "setMinimumDeposit(address,uint256)": FunctionFragment;
    "supportedAsset(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addSupportedAsset"
      | "admin"
      | "deployReceiver"
      | "getMinimumDeposit"
      | "minimumDeposit"
      | "participatingInterface"
      | "portal"
      | "receiver"
      | "setMinimumDeposit"
      | "supportedAsset"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addSupportedAsset",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deployReceiver",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMinimumDeposit",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "minimumDeposit",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "participatingInterface",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "portal", values?: undefined): string;
  encodeFunctionData(functionFragment: "receiver", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMinimumDeposit",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedAsset",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSupportedAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deployReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMinimumDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minimumDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "participatingInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "portal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "receiver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedAsset",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AssetChainManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AssetChainManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addSupportedAsset(
      _asset: string,
      _approved: string,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    admin(overrides?: CallOverrides): Promise<[string]>;

    deployReceiver(
      _lzEndpoint: string,
      _lzProcessingChainId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    getMinimumDeposit(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    minimumDeposit(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    participatingInterface(overrides?: CallOverrides): Promise<[string]>;

    portal(overrides?: CallOverrides): Promise<[string]>;

    receiver(overrides?: CallOverrides): Promise<[string]>;

    setMinimumDeposit(
      _asset: string,
      _minimum: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<ContractTransaction>;

    supportedAsset(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  addSupportedAsset(
    _asset: string,
    _approved: string,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  admin(overrides?: CallOverrides): Promise<string>;

  deployReceiver(
    _lzEndpoint: string,
    _lzProcessingChainId: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  getMinimumDeposit(
    _asset: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  minimumDeposit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  participatingInterface(overrides?: CallOverrides): Promise<string>;

  portal(overrides?: CallOverrides): Promise<string>;

  receiver(overrides?: CallOverrides): Promise<string>;

  setMinimumDeposit(
    _asset: string,
    _minimum: BigNumberish,
    overrides?: Overrides & { from?: string }
  ): Promise<ContractTransaction>;

  supportedAsset(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    addSupportedAsset(
      _asset: string,
      _approved: string,
      overrides?: CallOverrides
    ): Promise<void>;

    admin(overrides?: CallOverrides): Promise<string>;

    deployReceiver(
      _lzEndpoint: string,
      _lzProcessingChainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getMinimumDeposit(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minimumDeposit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    participatingInterface(overrides?: CallOverrides): Promise<string>;

    portal(overrides?: CallOverrides): Promise<string>;

    receiver(overrides?: CallOverrides): Promise<string>;

    setMinimumDeposit(
      _asset: string,
      _minimum: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    supportedAsset(arg0: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    addSupportedAsset(
      _asset: string,
      _approved: string,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    admin(overrides?: CallOverrides): Promise<BigNumber>;

    deployReceiver(
      _lzEndpoint: string,
      _lzProcessingChainId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    getMinimumDeposit(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    minimumDeposit(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    participatingInterface(overrides?: CallOverrides): Promise<BigNumber>;

    portal(overrides?: CallOverrides): Promise<BigNumber>;

    receiver(overrides?: CallOverrides): Promise<BigNumber>;

    setMinimumDeposit(
      _asset: string,
      _minimum: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<BigNumber>;

    supportedAsset(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addSupportedAsset(
      _asset: string,
      _approved: string,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    admin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    deployReceiver(
      _lzEndpoint: string,
      _lzProcessingChainId: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    getMinimumDeposit(
      _asset: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    minimumDeposit(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    participatingInterface(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    portal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiver(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setMinimumDeposit(
      _asset: string,
      _minimum: BigNumberish,
      overrides?: Overrides & { from?: string }
    ): Promise<PopulatedTransaction>;

    supportedAsset(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
